name: 'Setup Local PostgreSQL'
description: 'Setup a PostgreSQL database without password'
author: 'Harmon'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/_/postgres for supported versions
  # and further details on input environment variables
  postgresql version:
    description: 'Version of PostgreSQL to use'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
